name: Generate README

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Run script
        run: python script.py

      - name: Commit changes
        run: |
          git config --local user.email "bozzhik@ya.ru"
          git config --local user.name "bozzhik"
          git add README.md
          git commit -m "👾 Update README.md" -m "This commit was made using Github Actions"
          git push
